### ISSUE TITLE
Error in your Bernie Sanders map

### ISSUE THREAD

**Issue by idsville** [Alexay/StateOfTheBern#6]
Hello,
I just opened your map from the Bernie Sanders toolkit and noticed a flaw. It says that the "blue" states on the map are those in which he is polling higher and that the "cyan" are those that he has won. Well, you might want to think about reassigning those colors, or at the very least renaming them. A lot of people will not be familiar with the word cyan, which is another term for blue, and it's a bit confusing to have two shades of blue representing different things. And at least on my map, the "blue" states don't appear blue at all, they are a flat grey.

**Comment by Alexay** [comment]
The gray states are states for which RCP doesn't have a polling average yet.
